import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2, Brain, Droplets, Leaf, Mountain, Trees, ChevronRight, RefreshCw, TriangleAlert } from 'lucide-react';
import { MobileLayout } from '../../layouts/MobileLayout';
import { RiskGauge } from '../../components/risk/RiskGauge';
import { RiskBadge } from '../../components/risk/RiskBadge';
import { riskService } from '../../services/riskService';
import type { RiskPrediction, PredictionInput } from '../../types';

type Step = 'form' | 'loading' | 'result';

const LAND_USES = ['Forest', 'Agricultural', 'Mixed Forest', 'Tea Garden', 'Residential', 'Developed'];
const SUSCEPTIBILITY = ['High', 'Moderate', 'Low'];

export default function AIPredictionPage() {
  const navigate = useNavigate();
  const [step, setStep] = useState<Step>('form');
  const [result, setResult] = useState<RiskPrediction | null>(null);
  const [error, setError] = useState('');
  const [form, setForm] = useState<PredictionInput>({
    location: 'Zone A — Darjeeling Hills',
    rainfall: 84,
    rainfallDuration: 24,
    soilMoisture: 71,
    slope: 38,
    elevation: 2150,
    landUse: 'Mixed Forest',
    historicalSusceptibility: 'High',
  });

  const handleChange = (field: keyof PredictionInput, value: string | number) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handlePredict = async () => {
    setStep('loading');
    setError('');
    try {
      const prediction = await riskService.predictRisk(form);
      setResult(prediction);
      setStep('result');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate prediction. Please try again.');
      setStep('form');
    }
  };

  if (step === 'loading') {
    return (
      <MobileLayout>
        <div className="flex flex-col items-center justify-center gap-6 min-h-[70vh]">
          <div className="relative w-24 h-24">
            <div className="absolute inset-0 rounded-full border-4 border-primary-container animate-spin border-t-primary" />
            <div className="absolute inset-3 rounded-full bg-surface-container flex items-center justify-center">
              <Brain className="w-8 h-8 text-primary" />
            </div>
          </div>
          <div className="text-center flex flex-col gap-2">
            <p className="text-headline-sm text-on-surface">Analyzing Parameters...</p>
            <p className="text-body-md text-on-surface-variant">AI model is processing environmental data</p>
            <div className="flex items-center gap-2 mt-3 px-4 py-2 bg-surface-container border border-outline-variant rounded-lg">
              <Loader2 className="w-4 h-4 text-primary animate-spin" />
              <span className="text-label-md text-on-surface-variant uppercase">Running risk inference...</span>
            </div>
          </div>
        </div>
      </MobileLayout>
    );
  }

  if (step === 'result' && result) {
    const ICONS: Record<string, React.ElementType> = {
      CloudRain: Droplets, Droplets, Mountain, History: RefreshCw, Trees,
    };

    return (
      <MobileLayout>
        <div className="flex flex-col gap-5">
          {/* Real data disclaimer */}
          <div className="bg-primary-container/20 border border-primary/30 rounded-lg px-3 py-2 flex items-center gap-2">
            <Brain className="w-4 h-4 text-primary shrink-0" />
            <p className="text-label-sm text-on-surface-variant">Prediction generated by the BHUSHAKTI AI risk engine.</p>
          </div>

          {/* Result header */}
          <div className="text-center flex flex-col gap-2">
            <h2 className="text-headline-sm text-on-surface">AI Risk Assessment</h2>
            <p className="text-body-md text-on-surface-variant">{result.location}</p>
          </div>

          {/* Gauge */}
          <div className="bg-surface-container border border-outline-variant rounded-xl p-6 flex flex-col items-center gap-4">
            <RiskGauge probability={result.probability} riskLevel={result.riskLevel} size="lg" />
            <RiskBadge level={result.riskLevel} />
          </div>

          {/* Risk factors */}
          <div className="bg-surface-container border border-outline-variant rounded-xl p-4 flex flex-col gap-3">
            <h3 className="text-headline-sm text-on-surface">Contributing Factors</h3>
            <div className="grid grid-cols-2 gap-2">
              {result.riskFactors.map(({ name, value, unit, level, icon }) => {
                const Icon = ICONS[icon] || Droplets;
                return (
                  <div key={name} className="bg-surface-container-high border border-outline-variant rounded-lg p-3 flex flex-col gap-2">
                    <div className="flex justify-between items-center">
                      <Icon className="w-4 h-4 text-on-surface-variant" />
                      <RiskBadge level={level as 'high' | 'moderate' | 'low'} />
                    </div>
                    <p className="text-label-sm text-on-surface-variant uppercase">{name}</p>
                    <p className="text-headline-sm text-on-surface">{value}{unit && <span className="text-body-md text-on-surface-variant ml-1">{unit}</span>}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Recommended actions */}
          <div className="bg-surface-container border border-outline-variant rounded-xl p-4 flex flex-col gap-3">
            <h3 className="text-headline-sm text-on-surface">Recommended Actions</h3>
            <ul className="flex flex-col gap-2">
              {result.recommendedActions.map((action, i) => (
                <li key={i} className="flex items-start gap-3 text-body-md text-on-surface-variant p-2 border-b border-outline-variant/30 last:border-0">
                  <span className="w-5 h-5 rounded-full bg-primary-container text-primary text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                  {action}
                </li>
              ))}
            </ul>
          </div>

          {/* Actions */}
          <div className="flex flex-col gap-2 pb-4">
            <button
              onClick={() => navigate('/response-priority')}
              className="w-full h-12 bg-on-background text-background text-label-md uppercase tracking-widest rounded-xl flex items-center justify-center gap-2 hover:opacity-90 transition-opacity active:scale-[0.98]"
            >
              View Response Priority
              <ChevronRight className="w-4 h-4" />
            </button>
            <button
              onClick={() => setStep('form')}
              className="w-full h-12 border border-outline-variant text-on-surface text-label-md uppercase tracking-widest rounded-xl flex items-center justify-center gap-2 hover:bg-surface-container-high transition-colors active:scale-[0.98]"
            >
              <RefreshCw className="w-4 h-4" />
              Run New Assessment
            </button>
          </div>
        </div>
      </MobileLayout>
    );
  }

  return (
    <MobileLayout>
      <div className="flex flex-col gap-5">
        {/* Header */}
        <div className="flex flex-col gap-1">
          <div className="flex items-center gap-2">
            <Brain className="w-6 h-6 text-primary" />
            <h2 className="text-headline-sm text-on-surface">AI Risk Assessment</h2>
          </div>
          <p className="text-body-md text-on-surface-variant">
            Input environmental parameters to generate a risk prediction
          </p>
        </div>

        {/* Form card */}
        <div className="bg-surface-container border border-outline-variant rounded-xl p-4 flex flex-col gap-5">
          {error && (
            <div className="bg-error-container/20 border border-error/50 rounded-lg p-3 text-label-sm text-error">
              {error}
            </div>
          )}

          {/* Location */}
          <div className="flex flex-col gap-2">
            <label className="text-label-md text-on-surface-variant uppercase tracking-wider">Location</label>
            <input
              value={form.location}
              onChange={(e) => handleChange('location', e.target.value)}
              className="h-11 px-3 bg-surface-bright border border-outline rounded-lg text-on-surface text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary"
            />
          </div>

          {/* Rainfall */}
          <div className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <label className="text-label-md text-on-surface-variant uppercase tracking-wider flex items-center gap-2">
                <Droplets className="w-4 h-4" /> Rainfall (24h)
              </label>
              <span className="text-headline-sm text-on-surface">{form.rainfall} <span className="text-body-md text-on-surface-variant">mm</span></span>
            </div>
            <input type="range" min={0} max={200} step={1} value={form.rainfall}
              onChange={(e) => handleChange('rainfall', Number(e.target.value))}
              className="w-full h-2 bg-surface-bright rounded-full accent-primary cursor-pointer" />
            <div className="flex justify-between text-label-sm text-on-surface-variant">
              <span>0 mm</span><span>200 mm</span>
            </div>
          </div>

          {/* Soil Moisture */}
          <div className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <label className="text-label-md text-on-surface-variant uppercase tracking-wider flex items-center gap-2">
                <Leaf className="w-4 h-4" /> Soil Moisture
              </label>
              <span className="text-headline-sm text-on-surface">{form.soilMoisture}<span className="text-body-md text-on-surface-variant ml-1">%</span></span>
            </div>
            <input type="range" min={0} max={100} step={1} value={form.soilMoisture}
              onChange={(e) => handleChange('soilMoisture', Number(e.target.value))}
              className="w-full h-2 bg-surface-bright rounded-full accent-primary cursor-pointer" />
            <div className="flex justify-between text-label-sm text-on-surface-variant">
              <span>0%</span><span>100%</span>
            </div>
          </div>

          {/* Slope */}
          <div className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <label className="text-label-md text-on-surface-variant uppercase tracking-wider flex items-center gap-2">
                <Mountain className="w-4 h-4" /> Slope
              </label>
              <span className="text-headline-sm text-on-surface">{form.slope}<span className="text-body-md text-on-surface-variant ml-1">°</span></span>
            </div>
            <input type="range" min={0} max={60} step={1} value={form.slope}
              onChange={(e) => handleChange('slope', Number(e.target.value))}
              className="w-full h-2 bg-surface-bright rounded-full accent-primary cursor-pointer" />
            <div className="flex justify-between text-label-sm text-on-surface-variant">
              <span>0°</span><span>60°</span>
            </div>
          </div>

          {/* Land Use */}
          <div className="flex flex-col gap-2">
            <label className="text-label-md text-on-surface-variant uppercase tracking-wider">Land Use</label>
            <select
              value={form.landUse}
              onChange={(e) => handleChange('landUse', e.target.value)}
              className="h-11 px-3 bg-surface-bright border border-outline rounded-lg text-on-surface text-body-md focus:outline-none focus:border-primary"
            >
              {LAND_USES.map((lu) => <option key={lu} value={lu}>{lu}</option>)}
            </select>
          </div>

          {/* Historical Susceptibility */}
          <div className="flex flex-col gap-2">
            <label className="text-label-md text-on-surface-variant uppercase tracking-wider">Historical Susceptibility</label>
            <div className="flex gap-2">
              {SUSCEPTIBILITY.map((s) => (
                <button
                  key={s}
                  type="button"
                  onClick={() => handleChange('historicalSusceptibility', s)}
                  className={`flex-1 h-10 rounded-lg border text-label-md font-semibold transition-colors ${
                    form.historicalSusceptibility === s
                      ? 'bg-primary-container border-primary/30 text-on-primary-container'
                      : 'bg-surface-bright border-outline text-on-surface-variant hover:bg-surface-container-high'
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* CTA */}
        <button
          onClick={handlePredict}
          className="w-full h-12 bg-on-background text-background text-label-md uppercase tracking-widest rounded-xl flex items-center justify-center gap-2 hover:opacity-90 transition-opacity active:scale-[0.98] font-semibold"
        >
          <Brain className="w-5 h-5" />
          Run AI Prediction
        </button>

        <p className="text-label-sm text-on-surface-variant text-center">
          Prediction powered by BHUSHAKTI AI Random Forest model
        </p>
      </div>
    </MobileLayout>
  );
}
