/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Design Token Colors (exact from DESIGN.md)
        "background": "#0b1326",
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c5c6cd",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "outline": "#8f9097",
        "outline-variant": "#45474c",
        "surface-tint": "#bcc7de",
        // Primary
        "primary": "#bcc7de",
        "on-primary": "#263143",
        "primary-container": "#1e293b",
        "on-primary-container": "#8590a6",
        "primary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-fixed": "#111c2d",
        "on-primary-fixed-variant": "#3c475a",
        "inverse-primary": "#545f73",
        // Secondary
        "secondary": "#b9c8de",
        "on-secondary": "#233143",
        "secondary-container": "#39485a",
        "on-secondary-container": "#a7b6cc",
        "secondary-fixed": "#d4e4fa",
        "secondary-fixed-dim": "#b9c8de",
        "on-secondary-fixed": "#0d1c2d",
        "on-secondary-fixed-variant": "#39485a",
        // Tertiary
        "tertiary": "#ddc39d",
        "on-tertiary": "#3e2e13",
        "tertiary-container": "#35260c",
        "on-tertiary-container": "#a38c6a",
        "tertiary-fixed": "#fadfb8",
        "tertiary-fixed-dim": "#ddc39d",
        "on-tertiary-fixed": "#271902",
        "on-tertiary-fixed-variant": "#564427",
        // Error
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Risk palette (functional)
        "risk-critical": "#EF4444",
        "risk-high": "#F97316",
        "risk-moderate": "#EAB308",
        "risk-low": "#22C55E",
        "on-background": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "container-padding": "16px",
        "unit": "4px",
        "gutter": "12px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "gauge-in": "gauge-in 1s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
      },
      keyframes: {
        "gauge-in": {
          from: { strokeDashoffset: "283" },
          to: { strokeDashoffset: "var(--gauge-offset)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(20px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
}
